package app.handlive.android.core.design.component

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.height
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.dp
import app.handlive.android.core.design.R

/**
 * The brand mark (the signal fire on its mountain) for the welcome screen: `hl_brand_mark` with its night
 * variant, generated by the hub's `tools/brand/build_brand_assets.py`. Decorative: the title next to it names
 * the app, so TalkBack skips the image.
 */
@Composable
fun HLBrandMark(modifier: Modifier = Modifier) {
    Image(
        painter = painterResource(R.drawable.hl_brand_mark),
        contentDescription = null,
        modifier = modifier.height(BrandMarkHeight),
    )
}

private val BrandMarkHeight = 72.dp
